"""Alembic environment.

Migrations connect as the Postgres superuser (`POSTGRES_USER`/`POSTGRES_PASSWORD`
from the compose `db` service — see `Settings.superuser_dsn_sync`), because
the very first migration creates the `app_owner`/`app_writer`/`ai_reader`
roles that later connections use. This is documented in
`api/alembic/versions/0001_initial_schema.py`.
"""

from __future__ import annotations

from logging.config import fileConfig

from sqlalchemy import engine_from_config, pool

from alembic import context
from stockticker.config import get_settings

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = None  # migrations are hand-written SQL, not autogenerated


def _database_url() -> str:
    url: str = get_settings().superuser_dsn_sync
    return url


def run_migrations_offline() -> None:
    context.configure(
        url=_database_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    configuration = config.get_section(config.config_ini_section) or {}
    configuration["sqlalchemy.url"] = _database_url()
    connectable = engine_from_config(configuration, prefix="sqlalchemy.", poolclass=pool.NullPool)

    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
