/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/chat': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Chat */
    post: operations['chat_api_v1_chat_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/companies/{cik}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Company */
    get: operations['get_company_api_v1_companies__cik__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/events': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Events */
    get: operations['list_events_api_v1_events_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/health/live': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health Live */
    get: operations['health_live_api_v1_health_live_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/health/ready': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health Ready */
    get: operations['health_ready_api_v1_health_ready_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/listings/{symbol}/bars': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Bars */
    get: operations['list_bars_api_v1_listings__symbol__bars_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/market': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Market */
    get: operations['list_market_api_v1_market_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/notes': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Notes */
    get: operations['list_notes_api_v1_notes_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/notes/{note_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Put Note */
    put: operations['put_note_api_v1_notes__note_id__put']
    post?: never
    /** Remove Note */
    delete: operations['remove_note_api_v1_notes__note_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/status': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Status */
    get: operations['status_api_v1_status_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * AiStatus
     * @description Owned end to end by the AI chat agent's `stockticker.ai.status.
     *     ai_status(settings)` (issue #7's agreed contract) -- this model just
     *     gives it a shape to return. `StatusResponse.ai` is null until that
     *     module exists and `api/routers/status.py` calls it.
     */
    AiStatus: {
      /** Enabled */
      enabled: boolean
      /** Limit Usd */
      limit_usd: number
      /** Spend Usd */
      spend_usd: number
    }
    /** BackfillProgress */
    BackfillProgress: {
      /** Listings Done */
      listings_done: number
      /** Listings Total */
      listings_total: number
    }
    /** Bar */
    Bar: {
      /** Adj Close */
      adj_close: string
      /** Close */
      close: string
      /** High */
      high: string
      /** Low */
      low: string
      /** Open */
      open: string
      /**
       * Trade Date
       * Format: date
       */
      trade_date: string
      /** Volume */
      volume: number
    }
    /**
     * BarsResponse
     * @description `timeframe` only ever `"1d"` today; echoed back so the client's cache
     *     key is unambiguous once intraday timeframes exist (system design §5).
     */
    BarsResponse: {
      /** Bars */
      bars: components['schemas']['Bar'][]
      /**
       * Timeframe
       * @constant
       */
      timeframe: '1d'
    }
    /** ChartSeries */
    ChartSeries: {
      /** Key */
      key: string
      /** Label */
      label: string
    }
    /** CompanyDetail */
    CompanyDetail: {
      /** Cik */
      cik: string
      /** Date Added */
      date_added: string | null
      /** First Bar Date */
      first_bar_date: string | null
      /** Headquarters */
      headquarters: string | null
      /** Is Active */
      is_active: boolean
      /** Listings */
      listings: components['schemas']['ListingSummary'][]
      market_cap: components['schemas']['MarketCapSummary'] | null
      /** Name */
      name: string
      /** Sector */
      sector: string
      /** Sub Industry */
      sub_industry: string | null
      /** Week 52 High */
      week_52_high: string | null
      /** Week 52 Low */
      week_52_low: string | null
    }
    /**
     * DataViewPart
     * @description The `data-view` stream part: a table or chart built from a result the
     *     model has seen. Documented here so the web app can generate its type.
     */
    DataViewPart: {
      /** Data */
      data:
        | components['schemas']['TableSpec']
        | components['schemas']['TimeseriesChartSpec']
      /** Id */
      id: string
      /**
       * Type
       * @default data-view
       * @constant
       */
      type: 'data-view'
    }
    /** Event */
    Event: {
      /** Cik */
      cik: string
      /** Details */
      details: {
        [key: string]: unknown
      }
      /**
       * Event Date
       * Format: date
       */
      event_date: string
      /** Id */
      id: number
      /**
       * Kind
       * @enum {string}
       */
      kind:
        | 'split'
        | 'reverse_split'
        | 'cash_dividend'
        | 'symbol_change'
        | 'spin_off'
        | 'filing_10k'
        | 'filing_10q'
        | 'filing_8k'
        | 'index_added'
      /** Source */
      source: string
      /** Source Ref */
      source_ref: string
      /** Symbol */
      symbol: string | null
      /** Title */
      title: string
    }
    /**
     * EventsPage
     * @description Keyset page of Events (system design §5, amended). A distinct
     *     subclass, not a bare `Page[Event]` alias, so the OpenAPI schema keeps
     *     the name `EventsPage` instead of a generic-mangled one.
     */
    EventsPage: {
      /** Items */
      items: components['schemas']['Event'][]
      /** Next Cursor */
      next_cursor?: string | null
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /**
     * HealthResponse
     * @description `/api/v1/health/live` only: proves the process is up, no DB call.
     */
    HealthResponse: {
      /**
       * Status
       * @constant
       */
      status: 'ok'
    }
    /** JobStatusEntry */
    JobStatusEntry: {
      /** Consecutive Failures */
      consecutive_failures: number
      /** Error Summary */
      error_summary: string | null
      /** Finished At */
      finished_at: string | null
      /** Job */
      job: string
      /** Last Success At */
      last_success_at: string | null
      /** Status */
      status:
        | (
            | 'running'
            | 'succeeded'
            | 'partial'
            | 'failed'
            | 'skipped_locked'
            | 'skipped'
          )
        | null
    }
    /** ListingSummary */
    ListingSummary: {
      /** Backfill Completed At */
      backfill_completed_at: string | null
      /** First Bar Date */
      first_bar_date: string | null
      /** Is Active */
      is_active: boolean
      /** Is Primary */
      is_primary: boolean
      /** Symbol */
      symbol: string
    }
    /** MarketCapSummary */
    MarketCapSummary: {
      /** Is Approx */
      is_approx: boolean
      /** Market Cap */
      market_cap: string
      /**
       * Shares As Of
       * Format: date
       */
      shares_as_of: string
    }
    /**
     * MarketClock
     * @description Null until the Alpaca agent wires up `fetch_market_clock` (see marketdata.py).
     */
    MarketClock: {
      /** Is Open */
      is_open: boolean
      /**
       * Next Close
       * Format: date-time
       */
      next_close: string
      /**
       * Next Open
       * Format: date-time
       */
      next_open: string
    }
    /**
     * MarketResponse
     * @description Reliability review: carries the same market-clock fields as
     *     `/api/v1/status` so the client never has to combine two cached queries
     *     to answer "is the market open" next to the listings themselves.
     */
    MarketResponse: {
      /** Listings */
      listings: components['schemas']['MarketRow'][]
      market_clock: components['schemas']['MarketClock'] | null
      /**
       * Server Time
       * Format: date-time
       */
      server_time: string
    }
    /** MarketRow */
    MarketRow: {
      /** Backfill Completed At */
      backfill_completed_at: string | null
      /** Change */
      change: string | null
      /** Change Pct */
      change_pct: string | null
      /** Cik */
      cik: string
      /** First Bar Date */
      first_bar_date: string | null
      /** Is Primary */
      is_primary: boolean
      /** Market Cap */
      market_cap: string | null
      /** Market Cap Is Approx */
      market_cap_is_approx: boolean
      /** Name */
      name: string
      /** Observed At */
      observed_at: string | null
      /** Prev Close */
      prev_close: string | null
      /** Price */
      price: string | null
      /** Sector */
      sector: string
      /** Symbol */
      symbol: string
      /** Volume */
      volume: number | null
    }
    /** Note */
    Note: {
      /** Body */
      body: string
      /** Cik */
      cik: string | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /**
       * End Date
       * Format: date
       */
      end_date: string
      /**
       * Id
       * Format: uuid
       */
      id: string
      /**
       * Start Date
       * Format: date
       */
      start_date: string
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string
    }
    /**
     * NotePut
     * @description Body of `PUT /api/v1/notes/{id}` (system design §5, amended: the
     *     client supplies the id in the path; PUT is an idempotent upsert that
     *     replaces the old POST/PATCH).
     *
     *     `end_date` is filled in from `start_date` by a `mode="before"`
     *     validator -- before pydantic's own type coercion runs -- so the field
     *     is an honest `date` (not `date | None`) by the time anything reads it;
     *     no `assert` needed downstream to convince the type checker it's set.
     */
    NotePut: {
      /** Body */
      body: string
      /** Cik */
      cik?: string | null
      /**
       * End Date
       * Format: date
       */
      end_date: string
      /**
       * Start Date
       * Format: date
       */
      start_date: string
    }
    /**
     * NotesPage
     * @description Keyset page of Notes (system design §5, amended). A distinct
     *     subclass, not a bare `Page[Note]` alias, so the OpenAPI schema keeps
     *     the name `NotesPage` instead of a generic-mangled one.
     */
    NotesPage: {
      /** Items */
      items: components['schemas']['Note'][]
      /** Next Cursor */
      next_cursor?: string | null
    }
    /** ProblemDetail */
    ProblemDetail: {
      /** Detail */
      detail?: string | null
      /**
       * Errors
       * @description Per-field validation errors, present on 422 responses.
       */
      errors?:
        | {
            [key: string]: unknown
          }[]
        | null
      /** Instance */
      instance?: string | null
      /** Status */
      status: number
      /** Title */
      title: string
      /**
       * Type
       * @default about:blank
       */
      type: string
    }
    /**
     * ReadyResponse
     * @description `/api/v1/health/ready`: DB reachable and schema at the Alembic head.
     */
    ReadyResponse: {
      /**
       * Database
       * @constant
       */
      database: 'ok'
      /**
       * Migration
       * @constant
       */
      migration: 'ok'
      /**
       * Status
       * @constant
       */
      status: 'ok'
    }
    /** StatusResponse */
    StatusResponse: {
      ai: components['schemas']['AiStatus'] | null
      backfill: components['schemas']['BackfillProgress']
      /** Data As Of */
      data_as_of: string | null
      /** Jobs */
      jobs: components['schemas']['JobStatusEntry'][]
      market_clock: components['schemas']['MarketClock'] | null
      /** Missing Keys */
      missing_keys: string[]
      /** Open Gaps */
      open_gaps: number
      /**
       * Server Time
       * Format: date-time
       */
      server_time: string
    }
    /** TableColumn */
    TableColumn: {
      /** Format */
      format?: string | null
      /** Key */
      key: string
      /** Label */
      label: string
    }
    /** TableSpec */
    TableSpec: {
      /** Columns */
      columns: components['schemas']['TableColumn'][]
      /** Id */
      id: string
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: 'table'
      /** Rows */
      rows: {
        [key: string]: unknown
      }[]
      /** Title */
      title: string
    }
    /** TimeseriesChartSpec */
    TimeseriesChartSpec: {
      /** Id */
      id: string
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: 'timeseries'
      /** Rows */
      rows: {
        [key: string]: unknown
      }[]
      /** Series */
      series: components['schemas']['ChartSeries'][]
      /** Title */
      title: string
      /** X */
      x: string
      /** Y Format */
      y_format?: string | null
    }
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>
      /** Input */
      input?: unknown
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  chat_api_v1_chat_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          id?: string | null
          messageId?: string | null
          messages: ({
            /** @default  */
            id?: string
            parts?: {
              [key: string]: unknown
            }[]
            /** @enum {string} */
            role: 'system' | 'user' | 'assistant'
          } & {
            [key: string]: unknown
          })[]
          trigger?: string | null
        } & {
          [key: string]: unknown
        }
      }
    }
    responses: {
      /** @description An AI SDK UI message stream (v1): `data: <json>` server-sent events, ending with `data: [DONE]`. The schema shown is the app-specific `data-view` part; the other parts are the AI SDK's own. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DataViewPart']
          'text/event-stream': components['schemas']['DataViewPart']
        }
      }
      /** @description Request Entity Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProblemDetail']
        }
      }
      /** @description Unsupported Media Type */
      415: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProblemDetail']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProblemDetail']
        }
      }
    }
  }
  get_company_api_v1_companies__cik__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        cik: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CompanyDetail']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProblemDetail']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProblemDetail']
        }
      }
    }
  }
  list_events_api_v1_events_get: {
    parameters: {
      query?: {
        cik?: string | null
        symbol?: string | null
        from?: string | null
        to?: string | null
        /** @description Comma-separated list of event kinds. */
        kind?: string | null
        limit?: number
        cursor?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EventsPage']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProblemDetail']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProblemDetail']
        }
      }
    }
  }
  health_live_api_v1_health_live_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
    }
  }
  health_ready_api_v1_health_ready_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ReadyResponse']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProblemDetail']
        }
      }
    }
  }
  list_bars_api_v1_listings__symbol__bars_get: {
    parameters: {
      query?: {
        from?: string | null
        to?: string | null
        timeframe?: '1d'
      }
      header?: never
      path: {
        symbol: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BarsResponse']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProblemDetail']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProblemDetail']
        }
      }
    }
  }
  list_market_api_v1_market_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MarketResponse']
        }
      }
    }
  }
  list_notes_api_v1_notes_get: {
    parameters: {
      query?: {
        cik?: string | null
        from?: string | null
        to?: string | null
        market_only?: boolean
        /** @description With cik, also return whole-market Notes (cik is null). */
        include_market?: boolean
        limit?: number
        cursor?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['NotesPage']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProblemDetail']
        }
      }
    }
  }
  put_note_api_v1_notes__note_id__put: {
    parameters: {
      query?: never
      header?: never
      path: {
        note_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['NotePut']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Note']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProblemDetail']
        }
      }
    }
  }
  remove_note_api_v1_notes__note_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        note_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  status_api_v1_status_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['StatusResponse']
        }
      }
    }
  }
}
