/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/health/live': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health Live */
    get: operations['health_live_api_v1_health_live_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/health/ready': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health Ready */
    get: operations['health_ready_api_v1_health_ready_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/status': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Status */
    get: operations['status_api_v1_status_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/market': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Market */
    get: operations['list_market_api_v1_market_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/companies/{cik}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Company */
    get: operations['get_company_api_v1_companies__cik__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/listings/{symbol}/bars': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Bars */
    get: operations['list_bars_api_v1_listings__symbol__bars_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/events': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Events */
    get: operations['list_events_api_v1_events_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/notes': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Notes */
    get: operations['list_notes_api_v1_notes_get']
    put?: never
    /** Create Note */
    post: operations['create_note_api_v1_notes_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/notes/{note_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Delete Note */
    delete: operations['delete_note_api_v1_notes__note_id__delete']
    options?: never
    head?: never
    /** Update Note */
    patch: operations['update_note_api_v1_notes__note_id__patch']
    trace?: never
  }
  '/api/v1/chat': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Chat */
    post: operations['chat_api_v1_chat_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** BackfillProgress */
    BackfillProgress: {
      /** Listings Done */
      listings_done: number
      /** Listings Total */
      listings_total: number
    }
    /** Bar */
    Bar: {
      /**
       * Trade Date
       * Format: date
       */
      trade_date: string
      /** Open */
      open: string
      /** High */
      high: string
      /** Low */
      low: string
      /** Close */
      close: string
      /** Volume */
      volume: number
      /** Adj Close */
      adj_close: string
    }
    /** CompanyDetail */
    CompanyDetail: {
      /** Cik */
      cik: string
      /** Name */
      name: string
      /** Sector */
      sector: string
      /** Sub Industry */
      sub_industry: string | null
      /** Headquarters */
      headquarters: string | null
      /** Date Added */
      date_added: string | null
      /** Is Active */
      is_active: boolean
      /** Listings */
      listings: components['schemas']['ListingSummary'][]
      market_cap: components['schemas']['MarketCapSummary'] | null
      /** Week 52 High */
      week_52_high: string | null
      /** Week 52 Low */
      week_52_low: string | null
      /** First Bar Date */
      first_bar_date: string | null
    }
    /** Event */
    Event: {
      /** Id */
      id: number
      /** Cik */
      cik: string
      /** Symbol */
      symbol: string | null
      /**
       * Event Date
       * Format: date
       */
      event_date: string
      /**
       * Kind
       * @enum {string}
       */
      kind:
        | 'split'
        | 'reverse_split'
        | 'cash_dividend'
        | 'symbol_change'
        | 'spin_off'
        | 'filing_10k'
        | 'filing_10q'
        | 'filing_8k'
        | 'index_added'
      /** Title */
      title: string
      /** Details */
      details: {
        [key: string]: unknown
      }
      /** Source */
      source: string
      /** Source Ref */
      source_ref: string
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /**
     * HealthResponse
     * @description `/api/v1/health/live` only: proves the process is up, no DB call.
     */
    HealthResponse: {
      /**
       * Status
       * @constant
       */
      status: 'ok'
    }
    /** JobStatusEntry */
    JobStatusEntry: {
      /** Job */
      job: string
      /** Status */
      status:
        | (
            | 'running'
            | 'succeeded'
            | 'partial'
            | 'failed'
            | 'skipped_locked'
            | 'skipped'
          )
        | null
      /** Finished At */
      finished_at: string | null
      /** Last Success At */
      last_success_at: string | null
      /** Consecutive Failures */
      consecutive_failures: number
      /** Error Summary */
      error_summary: string | null
    }
    /** ListingSummary */
    ListingSummary: {
      /** Symbol */
      symbol: string
      /** Is Primary */
      is_primary: boolean
      /** Is Active */
      is_active: boolean
      /** First Bar Date */
      first_bar_date: string | null
    }
    /** MarketCapSummary */
    MarketCapSummary: {
      /** Market Cap */
      market_cap: string
      /**
       * Shares As Of
       * Format: date
       */
      shares_as_of: string
      /** Is Approx */
      is_approx: boolean
    }
    /**
     * MarketClock
     * @description Null until the Alpaca agent wires up `fetch_market_clock` (see marketdata.py).
     */
    MarketClock: {
      /** Is Open */
      is_open: boolean
      /**
       * Next Open
       * Format: date-time
       */
      next_open: string
      /**
       * Next Close
       * Format: date-time
       */
      next_close: string
    }
    /**
     * MarketResponse
     * @description Reliability review: carries the same market-clock fields as
     *     `/api/v1/status` so the client never has to combine two cached queries
     *     to answer "is the market open" next to the listings themselves.
     */
    MarketResponse: {
      /**
       * Server Time
       * Format: date-time
       */
      server_time: string
      market_clock: components['schemas']['MarketClock'] | null
      /** Listings */
      listings: components['schemas']['MarketRow'][]
    }
    /** MarketRow */
    MarketRow: {
      /** Symbol */
      symbol: string
      /** Cik */
      cik: string
      /** Name */
      name: string
      /** Sector */
      sector: string
      /** Price */
      price: string | null
      /** Observed At */
      observed_at: string | null
      /** Prev Close */
      prev_close: string | null
      /** Change */
      change: string | null
      /** Change Pct */
      change_pct: string | null
      /** Volume */
      volume: number | null
      /** Market Cap */
      market_cap: string | null
      /** Market Cap Is Approx */
      market_cap_is_approx: boolean
      /** First Bar Date */
      first_bar_date: string | null
    }
    /** Note */
    Note: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Cik */
      cik: string | null
      /**
       * Start Date
       * Format: date
       */
      start_date: string
      /**
       * End Date
       * Format: date
       */
      end_date: string
      /** Body */
      body: string
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string
    }
    /** NoteCreate */
    NoteCreate: {
      /** Cik */
      cik?: string | null
      /**
       * Start Date
       * Format: date
       */
      start_date: string
      /** End Date */
      end_date?: string | null
      /** Body */
      body: string
    }
    /**
     * NoteUpdate
     * @description Partial update. A field omitted from the request body is left
     *     unchanged; the router applies this with `model_dump(exclude_unset=True)`,
     *     so an explicit `null` for `cik` clears it (market-wide note).
     */
    NoteUpdate: {
      /** Cik */
      cik?: string | null
      /** Start Date */
      start_date?: string | null
      /** End Date */
      end_date?: string | null
      /** Body */
      body?: string | null
    }
    /** ProblemDetail */
    ProblemDetail: {
      /**
       * Type
       * @default about:blank
       */
      type: string
      /** Title */
      title: string
      /** Status */
      status: number
      /** Detail */
      detail?: string | null
      /** Instance */
      instance?: string | null
      /**
       * Errors
       * @description Per-field validation errors, present on 422 responses.
       */
      errors?:
        | {
            [key: string]: unknown
          }[]
        | null
    }
    /** ReadyResponse */
    ReadyResponse: {
      /**
       * Status
       * @constant
       */
      status: 'ok'
      /**
       * Database
       * @constant
       */
      database: 'ok'
      /**
       * Migration
       * @constant
       */
      migration: 'ok'
    }
    /** StatusResponse */
    StatusResponse: {
      /**
       * Server Time
       * Format: date-time
       */
      server_time: string
      market_clock: components['schemas']['MarketClock'] | null
      /** Jobs */
      jobs: components['schemas']['JobStatusEntry'][]
      backfill: components['schemas']['BackfillProgress']
      /** Missing Keys */
      missing_keys: string[]
      /** Data As Of */
      data_as_of: string | null
      /** Open Gaps */
      open_gaps: number
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  health_live_api_v1_health_live_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
    }
  }
  health_ready_api_v1_health_ready_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ReadyResponse']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProblemDetail']
        }
      }
    }
  }
  status_api_v1_status_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['StatusResponse']
        }
      }
    }
  }
  list_market_api_v1_market_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MarketResponse']
        }
      }
      /** @description Not Implemented */
      501: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProblemDetail']
        }
      }
    }
  }
  get_company_api_v1_companies__cik__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        cik: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CompanyDetail']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProblemDetail']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
      /** @description Not Implemented */
      501: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProblemDetail']
        }
      }
    }
  }
  list_bars_api_v1_listings__symbol__bars_get: {
    parameters: {
      query?: {
        from?: string | null
        to?: string | null
      }
      header?: never
      path: {
        symbol: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Bar'][]
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProblemDetail']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
      /** @description Not Implemented */
      501: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProblemDetail']
        }
      }
    }
  }
  list_events_api_v1_events_get: {
    parameters: {
      query?: {
        cik?: string | null
        from?: string | null
        to?: string | null
        /** @description Comma-separated list of event kinds. */
        kind?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Event'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
      /** @description Not Implemented */
      501: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProblemDetail']
        }
      }
    }
  }
  list_notes_api_v1_notes_get: {
    parameters: {
      query?: {
        cik?: string | null
        from?: string | null
        to?: string | null
        market_only?: boolean
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Note'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
      /** @description Not Implemented */
      501: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProblemDetail']
        }
      }
    }
  }
  create_note_api_v1_notes_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['NoteCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Note']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProblemDetail']
        }
      }
      /** @description Not Implemented */
      501: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProblemDetail']
        }
      }
    }
  }
  delete_note_api_v1_notes__note_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        note_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProblemDetail']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
      /** @description Not Implemented */
      501: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProblemDetail']
        }
      }
    }
  }
  update_note_api_v1_notes__note_id__patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        note_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['NoteUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Note']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProblemDetail']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
      /** @description Not Implemented */
      501: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProblemDetail']
        }
      }
    }
  }
  chat_api_v1_chat_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Not Implemented */
      501: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProblemDetail']
        }
      }
    }
  }
}
